### ISSUE TITLE
Error: Failed to apply catalog: Could not find dependency User[user] for Exec[su -c 'curl -L https://get.rvm.io | bash -s stable' - user] at /etc/puppet/modules/single_user_rvm/manifests/install.pp:97

### ISSUE THREAD

**Issue by evserykh** [DracoBlue/puppet-rvm#4]
Puppet 3.7.5

**Comment by DracoBlue** [comment]
@evserykh How does your rvm definition look like? Does the user exist?

**Comment by evserykh** [comment]
```ruby
node 'agent0' {
  rvm::ruby { 'sev':
  user => 'user',
  version => '2.1'
}
```

The user does exist. I try this one on Puppet 3.6.2 and Puppet 3.7.5 - both the same.

**Comment by DracoBlue** [comment]
Is the user created with User{ "user": ... } somewhere? Ist the user really
called "user"? If the user is "sev", please change to user => "sev",.

The single user rvm module expects this to exist in your manifest.

Am Mittwoch, 15. April 2015 schrieb Evgeniy Serykh :

> node 'agent0' {
>   rvm::ruby { 'sev':
>   user => 'user',
>   version => '2.1'
> }
>
> The user does exist. I try this one on Puppet 3.6.2 and Puppet 3.7.5 -
> both the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DracoBlue/puppet-rvm/issues/4#issuecomment-93284663>.
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
I would put a


``` puppet
User { "user":
}
```

right before the rvm ruby definition, if you dont't create the user with puppet, yet.

**Comment by evserykh** [comment]
Dude, I'm sorry for confusing you with the user's name. But user for which I try to install Rvm exists. It's not about user. 

It's something about dependencies. I try to debug it. When I haven't curl or gpg on my system recipe doesn't install them. I try it several times on clean system. Or 'rvm-fix-to-install-single-user-rvm-gpg-key' trick doesn't apply. Puppet output gives little information. 

When I run commands manually all is fine.

**Comment by DracoBlue** [comment]
No problem :).

``` 
Failed to apply catalog: Could not find dependency User[user] for Exec[su -c 'curl -L https://get.rvm.io | bash -s stable' - user] at /etc/puppet/modules/single_user_rvm/manifests/install.pp:97
```

Is this still the error message?  If you still have this error, please try to put:

``` puppet
User { "user":
}
```

Because https://github.com/eirc/puppet-single_user_rvm/blob/master/manifests/install.pp#L96 requires User["user"] to be existant in your puppet manifest. Because it says:

``` puppet
  exec { $install_command:
    path    => '/usr/bin:/usr/sbin:/bin',
    creates => "${homedir}/.rvm/bin/rvm",
    require => [ Package['curl'], Package['bash'], User[$user] ], # <<-- here is User["user"] required
  }```

**Comment by evserykh** [comment]
It seems 
```
user { "user":
}
```
helps.

Thanks a lot

**Comment by DracoBlue** [comment]
Good ;).
